# Generated by Django 3.2.10 on 2022-01-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_user_d_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodename', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'all node',
                'verbose_name_plural': 'node',
            },
        ),
    ]
