# Generated by Django 3.2.10 on 2022-01-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_node'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': 'nodes', 'verbose_name_plural': 'node'},
        ),
    ]
