# Generated by Django 3.2.10 on 2022-01-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_alter_node_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': '服务器们', 'verbose_name_plural': '服务器'},
        ),
    ]
